"""
Stub file for mathutils module to provide type hints for VSCode.
This file provides basic type definitions for Blender's mathutils module.
"""

from typing import Any, List, Tuple, Union, Iterator

class Vector:
    x: float
    y: float
    z: float
    
    def __init__(self, seq: Union[Tuple[float, float, float], List[float]]) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __add__(self, other: 'Vector') -> 'Vector': ...
    def __sub__(self, other: 'Vector') -> 'Vector': ...
    def __mul__(self, scalar: float) -> 'Vector': ...


class Euler:
    x: float
    y: float
    z: float
    order: str

    def __init__(self, angles: Tuple[float, float, float], order: str = 'XYZ') -> None: ...
